repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
    repo: https://github.com/tox-dev/tox
    rev: 3.6.0
    hooks:
    -   id: tox
        name: tox
        entry: tox
        verbose: true
        pass_filenames: false
        description: Automated tests using tox